name: "locations"
label: "Locations"
create: true
folder: "src/content/locations"
fields:
  - label: "Title"
    name: "title"
    widget: "string"
  - label: "Address"
    name: "address"
    widget: "object"
    fields:
      - label: "Street Address"
        name: "street"
        widget: "string"
      - label: "City"
        name: "city"
        widget: "string"
      - label: "County"
        name: "county"
        widget: "string"
      - label: "Postcode"
        name: "postcode"
        widget: "string"

  - label: "Phone"
    name: "phone"
    widget: "object"
    fields:
      - label: "Office Hours"
        name: "office-hours"
        widget: "string"
      - label: "Out Of Hours"
        name: "out-of-hours"
        widget: "string"

  - label: "Directions and Parking"
    name: "directions"
    widget: "text"

  - label: "Disabled Access"
    name: "disabled-access"
    widget: "text"
