label: "About Us"
name: "about"
file: "content/pages/about-us.md"
fields:
  - label: Title
    name: title
    default: About Us
    widget: string
  - label: Content
    name: body
    widget: markdown
  - label: "Layout"
    name: layout
    default: "page.pug"
    widget: hidden
  - label: "Permalink"
    name: permalink
    default: "about"
    widget: hidden
