name: services
label: Services
label-singular: Service
folder: "src/content/services"
create: true
extension: md
fields:
  - label: Title
    name: title
    widget: string
  - label: Short Summary
    name: summary
    widget: text
  - label: Description
    name: body
    widget: markdown
