backend:
  name:
  repo:
media_folder: "src/images/uploads"
public: "/images/uploads"
display_url:
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  # Load collection configs from separate files because it's smart.
  # - !!inc/file config/collections/file.yml
